#!/usr/bin/python3

import aoc_util
import sys
import os
import stat

if len(sys.argv) != 5:
    print('syntax: aoc_submit {year} {day} {part} {answer}')
    exit(1)

year = int(sys.argv[1])
day = int(sys.argv[2])
part = int(sys.argv[3])
answer = sys.argv[4]

if (year < 2018) or (year > 2023):
    print(f'Year: {year} should probably be in [2018,2023]')
    exit(1)
if (day < 1) or (day > 31):
    print(f'Day: {day} should be in [1,31]')
    exit(1)
if part not in (1,2):
    print(f'Part: {part} should be 1 or 2')
    exit(1)

result = aoc_util.submit_answer(year, day, part, answer)

print(result)
